version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  webui:
    build:
      context: .
      dockerfile: ./Presentation/DynamicConfiguration.WebUI/Dockerfile
    image: dynamic-configuration-webui:latest
    container_name: dynamic-configuration-webui
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      DOTNET_ENVIRONMENT: Development
      REDIS_CONNECTION_STRING: "redis:6379"
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"
      MONGODB_CONNECTION_STRING: "mongodb://root:root@mongodb:27017"

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
